export interface MotivationalQuote {
  text: string;
  author?: string;
}

export const MOTIVATIONAL_QUOTES: MotivationalQuote[] = [
  { text: "Rome was not built in a day, but they were laying bricks every hour.", author: "John Heywood" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "What you get by achieving your goals is not as important as what you become.", author: "Henry David Thoreau" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Success is not final, failure is not fatal — it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Do not go where the path may lead; go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "In order to be irreplaceable, one must always be different.", author: "Coco Chanel" },
  { text: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Maya Angelou" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
  { text: "Don't judge each day by the harvest you reap, but by the seeds that you plant.", author: "Robert Louis Stevenson" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Whether you think you can or think you can't, you're right.", author: "Henry Ford" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "An unexamined life is not worth living.", author: "Socrates" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
  { text: "When you stand at the edge of all the light you know and are about to step off into the darkness of the unknown, faith is knowing one of two things will happen: there will be something solid to stand on, or you will be taught to fly.", author: "Patrick Overton" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { text: "Love the life you live. Live the life you love.", author: "Bob Marley" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas A. Edison" },
  { text: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },
  { text: "If life were predictable it would cease to be life and be without flavor.", author: "Eleanor Roosevelt" },
  { text: "If you look at what you have in life, you'll always have more.", author: "Oprah Winfrey" },
  { text: "If you want to achieve greatness stop asking for permission.", author: "Anonymous" },
  { text: "Things work out best for those who make the best of how things work out.", author: "John Wooden" },
  { text: "To live a creative life, we must lose our fear of being wrong.", author: "Joseph Chilton Pearce" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { text: "Trust because you are willing to accept the risk, not because it's safe or certain.", author: "Anonymous" },
  { text: "Take up one idea. Make that one idea your life — think of it, dream of it, live on that idea.", author: "Swami Vivekananda" },
  { text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },
  { text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Anonymous" },
  { text: "If you do what you always did, you will get what you always got.", author: "Anonymous" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "Just when the caterpillar thought the world was ending, he turned into a butterfly.", author: "Anonymous" },
  { text: "Successful entrepreneurs are givers and not takers of positive energy.", author: "Anonymous" },
  { text: "Whenever you see a successful person, you only see the public glories, never the private sacrifices.", author: "Vaibhav Shah" },
  { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
  { text: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
  { text: "If you don't value your time, neither will others. Stop giving away your time and talents.", author: "Kim Garst" },
  { text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "The difference between who you are and who you want to be is what you do.", author: "Anonymous" },
  { text: "The distance between dreams and reality is called action.", author: "Anonymous" },
  { text: "You already survived 100% of your hardest days.", author: "Anonymous" },
  { text: "The version of you from a year ago would be proud of where you are today.", author: "Velvet" },
  { text: "Progress is just consistency wearing a disguise.", author: "Velvet" },
  { text: "The longer the climb, the better the view looks when you stop to breathe.", author: "Velvet" },
  { text: "You are not behind — you are on your own timeline.", author: "Velvet" },
  { text: "The door you keep walking past might be the one you were meant to open.", author: "Velvet" },
  { text: "Rest is not quitting. It is reloading.", author: "Velvet" },
  { text: "Every expert was once a beginner who refused to stay one.", author: "Velvet" },
  { text: "The right people will find you when you stop shrinking for the wrong ones.", author: "Velvet" },
  { text: "Doubt is just ambition asking for permission.", author: "Velvet" },
  { text: "The loudest room in the world cannot quiet a made-up mind.", author: "Velvet" },
  { text: "Your comeback is always louder than your setback.", author: "Velvet" },
  { text: "The storm you are weathering is building the strength you will need later.", author: "Velvet" },
  { text: "What looks like the wrong turn sometimes leads to the most beautiful destination.", author: "Velvet" },
  { text: "You were not made to blend in. You were made to stand out in exactly the right room.", author: "Velvet" },
  { text: "The life you want is on the other side of the fear you keep feeding.", author: "Velvet" },
  { text: "Some days you plant. Some days you water. Trust the season you are in.", author: "Velvet" },
  { text: "The quietest revolution is the one you start inside yourself.", author: "Velvet" },
  { text: "Every single day you show up is a vote for the person you are becoming.", author: "Velvet" },
  { text: "Your story is not over — you are still in the middle of the best chapter.", author: "Velvet" },
  { text: "The world gets better when you get better. Start there.", author: "Velvet" },
  { text: "You do not need everyone to understand your journey. You just need to keep walking it.", author: "Velvet" },
  { text: "The most powerful words you can speak are the ones you tell yourself in the dark.", author: "Velvet" },
  { text: "One day at a time is not a limit — it is a superpower.", author: "Velvet" },
  { text: "Pressure makes diamonds. You are being refined, not destroyed.", author: "Velvet" },
  { text: "Stillness is not emptiness. Sometimes the bravest thing is sitting with yourself.", author: "Velvet" },
  { text: "A flower does not compete with the flower next to it. It just blooms.", author: "Zen Proverb" },
  { text: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.", author: "Robert Frost" },
  { text: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou" },
  { text: "The greatest pleasure in life is doing what people say you cannot do.", author: "Walter Bagehot" },
  { text: "Life is short, and it is here to be lived.", author: "Kate Winslet" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Money and success don't change people; they merely amplify what is already there.", author: "Will Smith" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "The only disability in life is a bad attitude.", author: "Scott Hamilton" },
  { text: "We must be willing to let go of the life we planned so as to have the life that is waiting for us.", author: "Joseph Campbell" },
  { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers.", author: "Socrates" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.", author: "Helen Keller" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author: "Plato" },
  { text: "Nothing is impossible, the word itself says 'I'm possible!'", author: "Audrey Hepburn" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Begin at the beginning, and go on till you come to the end; then stop.", author: "Lewis Carroll" },
  { text: "Life is 10% what happens to me and 90% of how I react to it.", author: "Charles Swindoll" },
  { text: "The most common form of despair is not being who you are.", author: "Søren Kierkegaard" },
  { text: "If you fell down yesterday, stand up today.", author: "H.G. Wells" },
];

export function getQuoteForSession(userId: string, loginDate: string): MotivationalQuote {
  const seed = userId + loginDate;
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    const char = seed.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash & hash;
  }
  const index = Math.abs(hash) % MOTIVATIONAL_QUOTES.length;
  return MOTIVATIONAL_QUOTES[index];
}
