/*
# Add memory_proposals table for dreaming passes

1. New Tables
- `memory_proposals`: Stores proposals generated by the dreaming passes
  (Pass A hygiene and Pass B fleet). Each proposal represents a suggested
  change to a memory item or system-level config (prompts, extraction rules,
  opener rules). Low-risk proposals are auto-applied; everything else
  requires human approval via the admin review queue.

2. Columns
- id (uuid PK)
- proposal_id (uuid, unique — generated by the dreaming function)
- pass (text — 'hygiene' | 'fleet')
- target (text — 'memory_item' | 'prompt:<name>' | 'extraction_rules' | 'opener_rules')
- target_id (text — memory_item uuid or config name)
- user_id (uuid, nullable — null for fleet-level proposals)
- companion_id (uuid, nullable — null for global proposals)
- action (text — 'supersede' | 'retire' | 'merge' | 'add' | 'edit')
- before (text — current state description)
- after (text — proposed new state)
- evidence (jsonb — array of message_id / memory_event_id references)
- prevalence (jsonb — { occurrences, sampled, rate })
- rationale (text — why this proposal was generated)
- risk (text — 'low' | 'medium' | 'high')
- base_version (int — for optimistic concurrency when applying)
- eval_delta (jsonb — { recall, false_memory } metrics)
- status (text — 'pending' | 'auto_applied' | 'approved' | 'rejected' | 'applied' | 'failed')
- applied_at (timestamptz, nullable)
- applied_by (uuid, nullable — admin user id who approved)
- created_at (timestamptz, default now())

3. Security
- RLS enabled.
- Users can SELECT their own proposals (user_id = auth.uid()).
- Admins (is_super_user) can SELECT all proposals.
- All writes via service role only (from edge functions / admin actions).
- Two SELECT policies: one for owner, one for super users.

4. Indexes
- (status, pass) for the admin review queue filtering
- (user_id, companion_id) for user-scoped lookups
*/

CREATE TABLE IF NOT EXISTS memory_proposals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id uuid UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  pass text NOT NULL CHECK (pass IN ('hygiene', 'fleet')),
  target text NOT NULL,
  target_id text NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  companion_id uuid,
  action text NOT NULL CHECK (action IN ('supersede', 'retire', 'merge', 'add', 'edit')),
  before text,
  after text,
  evidence jsonb DEFAULT '[]'::jsonb,
  prevalence jsonb DEFAULT '{}'::jsonb,
  rationale text,
  risk text NOT NULL DEFAULT 'medium' CHECK (risk IN ('low', 'medium', 'high')),
  base_version int,
  eval_delta jsonb,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'auto_applied', 'approved', 'rejected', 'applied', 'failed')),
  applied_at timestamptz,
  applied_by uuid,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE memory_proposals ENABLE ROW LEVEL SECURITY;

-- Users can see their own proposals
DROP POLICY IF EXISTS "select_own_proposals" ON memory_proposals;
CREATE POLICY "select_own_proposals"
ON memory_proposals FOR SELECT
TO authenticated
USING (user_id = auth.uid());

-- Super users can see all proposals
DROP POLICY IF EXISTS "select_all_proposals_admin" ON memory_proposals;
CREATE POLICY "select_all_proposals_admin"
ON memory_proposals FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM user_profiles
    WHERE id = auth.uid() AND COALESCE(is_super_user, false) = true
  )
);

CREATE INDEX IF NOT EXISTS idx_memory_proposals_status_pass
ON memory_proposals (status, pass);

CREATE INDEX IF NOT EXISTS idx_memory_proposals_user
ON memory_proposals (user_id, companion_id)
WHERE user_id IS NOT NULL;
